### ISSUE TITLE
Remote Defender goes to the wrong room in remote invasion (with 2+ remotes)

### ISSUE THREAD

**Issue by jakesboy2** [KungFuKlan/KungFuScreeps#29]
Remote defender targets the wrong room, from what I could tell, fairly consistently.
We need to figure out why.

Location of problem to solve will be found in the getTargetRoom implementation of RemoteDefenderBodyOptsHelper

**Comment by UhmBrock** [comment]
Due to military rework, this bug is no longer applicable.
