### ISSUE TITLE
Create implementation objects for runSquad

### ISSUE THREAD

**Issue by jakesboy2** [KungFuKlan/KungFuScreeps#63]
- [x] Create the object on each squad manager for each squad type that the manager supports. For now, we can just insert an empty runSquad into it. 

- [x] DomesticDefender
  - [x] FFA
  - [x] Combined
- [x] RemoteDefender
  - [x] FFA
  - [x] Combined
- [x] SoloZealot
  - [x] FFA
  - [x] Combined
- [x] SoloStalker
  - [x] FFA
  - [x] Combined
- [x] Standard Squad
  - [x] FFA
  - [x] Combined
- [x] TowerDrainer
  - [x] FFA
  - [x] Combined

**Comment by UhmBrock** [comment]
Completed my dude
